<?php declare(strict_types=1);

// ┌──────────────────────────────────────────────────────────────────────────┐
// │  AUTO-GENERATED — do not edit by hand.                                   │
// │  Source: extension/types/phpx-intrinsics.d.ts                             │
// │  Generator: extension/scripts/generate-html-attributes.ts                  │
// │  Run:  cd extension && pnpm exec tsx scripts/generate-html-attributes.ts  │
// └──────────────────────────────────────────────────────────────────────────┘

namespace Attitude\PHPX\LanguageServer;

final class HTMLAttributes
{
    /**
     * Get attributes for a specific HTML element, merged with common attributes.
     *
     * @return array<string, array{string, string}>  attrName => [type, description]
     */
    public static function forElement(string $tagName): array
    {
        return array_merge(
            self::COMMON,
            self::ELEMENT_SPECIFIC[$tagName] ?? [],
        );
    }

    /**
     * Look up a single attribute on a specific element.
     *
     * @return array{string, string}|null  [type, description] or null
     */
    public static function lookup(string $tagName, string $attrName): ?array
    {
        return self::ELEMENT_SPECIFIC[$tagName][$attrName]
            ?? self::COMMON[$attrName]
            ?? null;
    }

    private const COMMON = [
        'children' => ['any', ''],
        'className' => ['string', 'Maps to the HTML `class` attribute'],
        'contentEditable' => ['boolean | \'inherit\' | \'plaintext-only\'', ''],
        'dangerouslySetInnerHTML' => ['{ __html: string }', ''],
        'dir' => ['\'ltr\' | \'rtl\' | \'auto\'', ''],
        'draggable' => ['boolean', ''],
        'exportparts' => ['string', ''],
        'hidden' => ['boolean', ''],
        'id' => ['string', ''],
        'inert' => ['boolean', ''],
        'is' => ['string', ''],
        'key' => ['string | number | null', ''],
        'lang' => ['string', ''],
        'nonce' => ['string', ''],
        'onAbort' => ['PHPXEventHandler<Event>', ''],
        'onAnimationEnd' => ['PHPXEventHandler<AnimationEvent>', ''],
        'onAnimationIteration' => ['PHPXEventHandler<AnimationEvent>', ''],
        'onAnimationStart' => ['PHPXEventHandler<AnimationEvent>', ''],
        'onAuxClick' => ['PHPXEventHandler<MouseEvent>', ''],
        'onBeforeInput' => ['PHPXEventHandler<InputEvent>', ''],
        'onBeforeToggle' => ['PHPXEventHandler<Event>', ''],
        'onBlur' => ['PHPXEventHandler<FocusEvent>', ''],
        'onChange' => ['PHPXEventHandler<Event>', ''],
        'onClick' => ['PHPXEventHandler<MouseEvent>', ''],
        'onContextMenu' => ['PHPXEventHandler<MouseEvent>', ''],
        'onCopy' => ['PHPXEventHandler<ClipboardEvent>', ''],
        'onCut' => ['PHPXEventHandler<ClipboardEvent>', ''],
        'onDoubleClick' => ['PHPXEventHandler<MouseEvent>', ''],
        'onDrag' => ['PHPXEventHandler<DragEvent>', ''],
        'onDragEnd' => ['PHPXEventHandler<DragEvent>', ''],
        'onDragEnter' => ['PHPXEventHandler<DragEvent>', ''],
        'onDragLeave' => ['PHPXEventHandler<DragEvent>', ''],
        'onDragOver' => ['PHPXEventHandler<DragEvent>', ''],
        'onDragStart' => ['PHPXEventHandler<DragEvent>', ''],
        'onDrop' => ['PHPXEventHandler<DragEvent>', ''],
        'onError' => ['PHPXEventHandler<ErrorEvent | Event>', ''],
        'onFocus' => ['PHPXEventHandler<FocusEvent>', ''],
        'onFocusIn' => ['PHPXEventHandler<FocusEvent>', ''],
        'onFocusOut' => ['PHPXEventHandler<FocusEvent>', ''],
        'onFullscreenChange' => ['PHPXEventHandler<Event>', ''],
        'onFullscreenError' => ['PHPXEventHandler<Event>', ''],
        'onGotPointerCapture' => ['PHPXEventHandler<PointerEvent>', ''],
        'onInput' => ['PHPXEventHandler<InputEvent>', ''],
        'onInvalid' => ['PHPXEventHandler<Event>', ''],
        'onKeyDown' => ['PHPXEventHandler<KeyboardEvent>', ''],
        'onKeyPress' => ['PHPXEventHandler<KeyboardEvent>', '@deprecated Use onKeyDown instead'],
        'onKeyUp' => ['PHPXEventHandler<KeyboardEvent>', ''],
        'onLoad' => ['PHPXEventHandler<Event>', ''],
        'onLostPointerCapture' => ['PHPXEventHandler<PointerEvent>', ''],
        'onMouseDown' => ['PHPXEventHandler<MouseEvent>', ''],
        'onMouseEnter' => ['PHPXEventHandler<MouseEvent>', ''],
        'onMouseLeave' => ['PHPXEventHandler<MouseEvent>', ''],
        'onMouseMove' => ['PHPXEventHandler<MouseEvent>', ''],
        'onMouseOut' => ['PHPXEventHandler<MouseEvent>', ''],
        'onMouseOver' => ['PHPXEventHandler<MouseEvent>', ''],
        'onMouseUp' => ['PHPXEventHandler<MouseEvent>', ''],
        'onPaste' => ['PHPXEventHandler<ClipboardEvent>', ''],
        'onPointerCancel' => ['PHPXEventHandler<PointerEvent>', ''],
        'onPointerDown' => ['PHPXEventHandler<PointerEvent>', ''],
        'onPointerEnter' => ['PHPXEventHandler<PointerEvent>', ''],
        'onPointerLeave' => ['PHPXEventHandler<PointerEvent>', ''],
        'onPointerMove' => ['PHPXEventHandler<PointerEvent>', ''],
        'onPointerOut' => ['PHPXEventHandler<PointerEvent>', ''],
        'onPointerOver' => ['PHPXEventHandler<PointerEvent>', ''],
        'onPointerUp' => ['PHPXEventHandler<PointerEvent>', ''],
        'onReset' => ['PHPXEventHandler<Event>', ''],
        'onScroll' => ['PHPXEventHandler<Event>', ''],
        'onScrollEnd' => ['PHPXEventHandler<Event>', ''],
        'onSelect' => ['PHPXEventHandler<Event>', ''],
        'onSelectionChange' => ['PHPXEventHandler<Event>', ''],
        'onSubmit' => ['PHPXEventHandler<SubmitEvent>', ''],
        'onToggle' => ['PHPXEventHandler<Event>', ''],
        'onTouchCancel' => ['PHPXEventHandler<TouchEvent>', ''],
        'onTouchEnd' => ['PHPXEventHandler<TouchEvent>', ''],
        'onTouchMove' => ['PHPXEventHandler<TouchEvent>', ''],
        'onTouchStart' => ['PHPXEventHandler<TouchEvent>', ''],
        'onTransitionCancel' => ['PHPXEventHandler<TransitionEvent>', ''],
        'onTransitionEnd' => ['PHPXEventHandler<TransitionEvent>', ''],
        'onTransitionStart' => ['PHPXEventHandler<TransitionEvent>', ''],
        'onWheel' => ['PHPXEventHandler<WheelEvent>', ''],
        'part' => ['string', ''],
        'popover' => ['\'auto\' | \'manual\' | \'\'', ''],
        'role' => ['string', ''],
        'slot' => ['string', ''],
        'spellCheck' => ['boolean', ''],
        'style' => ['PHPXStyle', ''],
        'tabIndex' => ['number', 'Maps to the HTML `tabindex` attribute'],
        'title' => ['string', ''],
        'translate' => ['\'yes\' | \'no\'', ''],
    ];

    private const ELEMENT_SPECIFIC = [
        'a' => [
            'download' => ['string | boolean', ''],
            'href' => ['string', ''],
            'hrefLang' => ['string', 'Maps to `hreflang`'],
            'ping' => ['string', ''],
            'referrerPolicy' => ['ReferrerPolicy', ''],
            'rel' => ['string', ''],
            'target' => ['\'_blank\' | \'_self\' | \'_parent\' | \'_top\' | (string & {})', ''],
            'type' => ['string', ''],
        ],
        'area' => [
            'alt' => ['string', ''],
            'coords' => ['string', ''],
            'download' => ['string', ''],
            'href' => ['string', ''],
            'referrerPolicy' => ['ReferrerPolicy', ''],
            'rel' => ['string', ''],
            'shape' => ['\'rect\' | \'circle\' | \'poly\' | \'default\'', ''],
            'target' => ['string', ''],
        ],
        'audio' => [
            'autoPlay' => ['boolean', 'Maps to `autoplay`'],
            'controls' => ['boolean', ''],
            'crossOrigin' => ['\'anonymous\' | \'use-credentials\' | \'\'', 'Maps to `crossorigin`'],
            'loop' => ['boolean', ''],
            'muted' => ['boolean', ''],
            'preload' => ['\'none\' | \'metadata\' | \'auto\' | \'\'', ''],
            'src' => ['string', ''],
        ],
        'base' => [
            'href' => ['string', ''],
            'target' => ['string', ''],
        ],
        'blockquote' => [
            'cite' => ['string', ''],
        ],
        'button' => [
            'autoFocus' => ['boolean', 'Maps to `autofocus`'],
            'disabled' => ['boolean', ''],
            'form' => ['string', ''],
            'formAction' => ['string', 'Maps to `formaction`'],
            'formEncType' => ['string', 'Maps to `formenctype`'],
            'formMethod' => ['\'get\' | \'post\'', 'Maps to `formmethod`'],
            'formNoValidate' => ['boolean', 'Maps to `formnovalidate`'],
            'formTarget' => ['string', 'Maps to `formtarget`'],
            'name' => ['string', ''],
            'popovertarget' => ['string', ''],
            'popovertargetaction' => ['\'hide\' | \'show\' | \'toggle\'', ''],
            'type' => ['\'button\' | \'submit\' | \'reset\'', ''],
            'value' => ['string', ''],
        ],
        'canvas' => [
            'height' => ['number', ''],
            'width' => ['number', ''],
        ],
        'circle' => [
            'fill' => ['string', ''],
            'opacity' => ['number | string', ''],
            'stroke' => ['string', ''],
            'strokeWidth' => ['number | string', ''],
            'transform' => ['string', ''],
        ],
        'col' => [
            'span' => ['number', ''],
        ],
        'data' => [
            'value' => ['string', ''],
        ],
        'del' => [
            'cite' => ['string', ''],
            'dateTime' => ['string', 'Maps to `datetime`'],
        ],
        'details' => [
            'name' => ['string', ''],
            'open' => ['boolean', ''],
        ],
        'dialog' => [
            'open' => ['boolean', ''],
        ],
        'ellipse' => [
            'fill' => ['string', ''],
            'opacity' => ['number | string', ''],
            'stroke' => ['string', ''],
            'strokeWidth' => ['number | string', ''],
            'transform' => ['string', ''],
        ],
        'embed' => [
            'height' => ['number | string', ''],
            'src' => ['string', ''],
            'type' => ['string', ''],
            'width' => ['number | string', ''],
        ],
        'fieldset' => [
            'disabled' => ['boolean', ''],
            'form' => ['string', ''],
            'name' => ['string', ''],
        ],
        'form' => [
            'acceptCharset' => ['string', ''],
            'action' => ['string', ''],
            'autoComplete' => ['\'on\' | \'off\' | (string & {})', 'Maps to `autocomplete`'],
            'encType' => ['\'application/x-www-form-urlencoded\' | \'multipart/form-data\' | \'text/plain\'', 'Maps to `enctype`'],
            'method' => ['\'get\' | \'post\' | \'dialog\'', ''],
            'name' => ['string', ''],
            'noValidate' => ['boolean', 'Maps to `novalidate`'],
            'rel' => ['string', ''],
            'target' => ['\'_blank\' | \'_self\' | \'_parent\' | \'_top\' | (string & {})', ''],
        ],
        'g' => [
            'fill' => ['string', ''],
            'opacity' => ['number | string', ''],
            'stroke' => ['string', ''],
            'strokeWidth' => ['number | string', ''],
            'transform' => ['string', ''],
        ],
        'html' => [
            'xmlns' => ['string', ''],
        ],
        'iframe' => [
            'allow' => ['string', ''],
            'allowFullScreen' => ['boolean', 'Maps to `allowfullscreen`'],
            'height' => ['number | string', ''],
            'loading' => ['\'eager\' | \'lazy\'', ''],
            'name' => ['string', ''],
            'referrerPolicy' => ['ReferrerPolicy', ''],
            'sandbox' => ['string', ''],
            'src' => ['string', ''],
            'srcDoc' => ['string', 'Maps to `srcdoc`'],
            'width' => ['number | string', ''],
        ],
        'img' => [
            'alt' => ['string', ''],
            'crossOrigin' => ['\'anonymous\' | \'use-credentials\' | \'\'', 'Maps to `crossorigin`'],
            'decoding' => ['\'sync\' | \'async\' | \'auto\'', ''],
            'fetchPriority' => ['\'high\' | \'low\' | \'auto\'', ''],
            'height' => ['number | string', ''],
            'isMap' => ['boolean', 'Maps to `ismap`'],
            'loading' => ['\'eager\' | \'lazy\'', ''],
            'referrerPolicy' => ['ReferrerPolicy', ''],
            'sizes' => ['string', ''],
            'src' => ['string', ''],
            'srcSet' => ['string', 'Maps to `srcset`'],
            'useMap' => ['string', 'Maps to `usemap`'],
            'width' => ['number | string', ''],
        ],
        'input' => [
            'accept' => ['string', ''],
            'alt' => ['string', ''],
            'autoComplete' => ['string', 'Maps to `autocomplete`'],
            'autoFocus' => ['boolean', 'Maps to `autofocus`'],
            'capture' => ['\'user\' | \'environment\' | boolean', ''],
            'checked' => ['boolean', ''],
            'defaultChecked' => ['boolean', ''],
            'defaultValue' => ['string | number', ''],
            'dirname' => ['string', ''],
            'disabled' => ['boolean', ''],
            'enterKeyHint' => ['\'enter\' | \'done\' | \'go\' | \'next\' | \'previous\' | \'search\' | \'send\'', 'Maps to `enterkeyhint`'],
            'form' => ['string', ''],
            'formAction' => ['string', 'Maps to `formaction`'],
            'formEncType' => ['string', 'Maps to `formenctype`'],
            'formMethod' => ['string', 'Maps to `formmethod`'],
            'formNoValidate' => ['boolean', 'Maps to `formnovalidate`'],
            'formTarget' => ['string', 'Maps to `formtarget`'],
            'height' => ['number | string', ''],
            'inputMode' => ['\'none\' | \'text\' | \'decimal\' | \'numeric\' | \'tel\' | \'search\' | \'email\' | \'url\'', 'Maps to `inputmode`'],
            'list' => ['string', ''],
            'max' => ['string | number', ''],
            'maxLength' => ['number', 'Maps to `maxlength`'],
            'min' => ['string | number', ''],
            'minLength' => ['number', 'Maps to `minlength`'],
            'multiple' => ['boolean', ''],
            'name' => ['string', ''],
            'pattern' => ['string', ''],
            'placeholder' => ['string', ''],
            'popoverTarget' => ['string', ''],
            'popoverTargetAction' => ['\'hide\' | \'show\' | \'toggle\'', ''],
            'readOnly' => ['boolean', 'Maps to `readonly`'],
            'required' => ['boolean', ''],
            'size' => ['number', ''],
            'src' => ['string', ''],
            'step' => ['string | number', ''],
            'type' => ['\'text\' | \'password\' | \'email\' | \'number\' | \'tel\' | \'url\' | \'search\'
         | \'date\' | \'time\' | \'datetime-local\' | \'month\' | \'week\' | \'color\'
         | \'range\' | \'file\' | \'checkbox\' | \'radio\' | \'submit\' | \'reset\'
         | \'button\' | \'image\' | \'hidden\' | (string & {})', ''],
            'value' => ['string | number', ''],
            'width' => ['number | string', ''],
        ],
        'ins' => [
            'cite' => ['string', ''],
            'dateTime' => ['string', 'Maps to `datetime`'],
        ],
        'label' => [
            'form' => ['string', ''],
            'htmlFor' => ['string', 'Maps to the HTML `for` attribute'],
        ],
        'line' => [
            'fill' => ['string', ''],
            'opacity' => ['number | string', ''],
            'stroke' => ['string', ''],
            'strokeWidth' => ['number | string', ''],
            'transform' => ['string', ''],
        ],
        'link' => [
            'as' => ['string', ''],
            'blocking' => ['string', ''],
            'color' => ['string', ''],
            'crossOrigin' => ['\'anonymous\' | \'use-credentials\' | \'\'', 'Maps to `crossorigin`'],
            'disabled' => ['boolean', ''],
            'fetchPriority' => ['\'high\' | \'low\' | \'auto\'', ''],
            'href' => ['string', ''],
            'hrefLang' => ['string', 'Maps to `hreflang`'],
            'imagesizes' => ['string', ''],
            'imagesrcset' => ['string', ''],
            'integrity' => ['string', ''],
            'media' => ['string', ''],
            'referrerPolicy' => ['ReferrerPolicy', ''],
            'rel' => ['string', ''],
            'sizes' => ['string', ''],
            'type' => ['string', ''],
        ],
        'map' => [
            'name' => ['string', ''],
        ],
        'meta' => [
            'charset' => ['string', ''],
            'content' => ['string', ''],
            'httpEquiv' => ['string', 'Maps to `http-equiv`'],
            'media' => ['string', ''],
            'name' => ['string', ''],
            'property' => ['string', ''],
        ],
        'meter' => [
            'form' => ['string', ''],
            'high' => ['number', ''],
            'low' => ['number', ''],
            'max' => ['number', ''],
            'min' => ['number', ''],
            'optimum' => ['number', ''],
            'value' => ['number', ''],
        ],
        'object' => [
            'data' => ['string', ''],
            'form' => ['string', ''],
            'height' => ['number | string', ''],
            'name' => ['string', ''],
            'type' => ['string', ''],
            'useMap' => ['string', 'Maps to `usemap`'],
            'width' => ['number | string', ''],
        ],
        'ol' => [
            'reversed' => ['boolean', ''],
            'start' => ['number', ''],
            'type' => ['\'1\' | \'a\' | \'A\' | \'i\' | \'I\'', ''],
        ],
        'optgroup' => [
            'disabled' => ['boolean', ''],
            'label' => ['string', ''],
        ],
        'option' => [
            'disabled' => ['boolean', ''],
            'label' => ['string', ''],
            'selected' => ['boolean', ''],
            'value' => ['string', ''],
        ],
        'output' => [
            'form' => ['string', ''],
            'htmlFor' => ['string', ''],
            'name' => ['string', ''],
        ],
        'param' => [
            'name' => ['string', ''],
            'value' => ['string', ''],
        ],
        'path' => [
            'clipRule' => ['\'nonzero\' | \'evenodd\'', ''],
            'd' => ['string', ''],
            'fill' => ['string', ''],
            'fillRule' => ['\'nonzero\' | \'evenodd\'', ''],
            'opacity' => ['number | string', ''],
            'stroke' => ['string', ''],
            'strokeWidth' => ['number | string', ''],
            'transform' => ['string', ''],
        ],
        'polygon' => [
            'fill' => ['string', ''],
            'opacity' => ['number | string', ''],
            'stroke' => ['string', ''],
            'strokeWidth' => ['number | string', ''],
            'transform' => ['string', ''],
        ],
        'polyline' => [
            'fill' => ['string', ''],
            'opacity' => ['number | string', ''],
            'stroke' => ['string', ''],
            'strokeWidth' => ['number | string', ''],
            'transform' => ['string', ''],
        ],
        'progress' => [
            'max' => ['number', ''],
            'value' => ['number', ''],
        ],
        'q' => [
            'cite' => ['string', ''],
        ],
        'rect' => [
            'fill' => ['string', ''],
            'opacity' => ['number | string', ''],
            'stroke' => ['string', ''],
            'strokeWidth' => ['number | string', ''],
            'transform' => ['string', ''],
        ],
        'script' => [
            'async' => ['boolean', ''],
            'blocking' => ['string', ''],
            'crossOrigin' => ['\'anonymous\' | \'use-credentials\' | \'\'', 'Maps to `crossorigin`'],
            'defer' => ['boolean', ''],
            'fetchPriority' => ['\'high\' | \'low\' | \'auto\'', ''],
            'integrity' => ['string', ''],
            'noModule' => ['boolean', 'Maps to `nomodule`'],
            'referrerPolicy' => ['ReferrerPolicy', ''],
            'src' => ['string', ''],
            'type' => ['string', ''],
        ],
        'select' => [
            'autoComplete' => ['string', 'Maps to `autocomplete`'],
            'autoFocus' => ['boolean', 'Maps to `autofocus`'],
            'defaultValue' => ['string | string[]', ''],
            'disabled' => ['boolean', ''],
            'form' => ['string', ''],
            'multiple' => ['boolean', ''],
            'name' => ['string', ''],
            'required' => ['boolean', ''],
            'size' => ['number', ''],
            'value' => ['string | string[]', ''],
        ],
        'source' => [
            'height' => ['number', ''],
            'media' => ['string', ''],
            'sizes' => ['string', ''],
            'src' => ['string', ''],
            'srcSet' => ['string', 'Maps to `srcset`'],
            'type' => ['string', ''],
            'width' => ['number', ''],
        ],
        'style' => [
            'blocking' => ['string', ''],
            'media' => ['string', ''],
            'scoped' => ['boolean', '@deprecated'],
            'type' => ['string', ''],
        ],
        'svg' => [
            'fill' => ['string', ''],
            'height' => ['number | string', ''],
            'opacity' => ['number | string', ''],
            'preserveAspectRatio' => ['string', ''],
            'stroke' => ['string', ''],
            'strokeLinecap' => ['\'butt\' | \'round\' | \'square\'', ''],
            'strokeLinejoin' => ['\'miter\' | \'round\' | \'bevel\'', ''],
            'strokeWidth' => ['number | string', ''],
            'transform' => ['string', ''],
            'viewBox' => ['string', ''],
            'width' => ['number | string', ''],
            'xmlns' => ['string', ''],
        ],
        'symbol' => [
            'fill' => ['string', ''],
            'height' => ['number | string', ''],
            'opacity' => ['number | string', ''],
            'preserveAspectRatio' => ['string', ''],
            'stroke' => ['string', ''],
            'strokeLinecap' => ['\'butt\' | \'round\' | \'square\'', ''],
            'strokeLinejoin' => ['\'miter\' | \'round\' | \'bevel\'', ''],
            'strokeWidth' => ['number | string', ''],
            'transform' => ['string', ''],
            'viewBox' => ['string', ''],
            'width' => ['number | string', ''],
            'xmlns' => ['string', ''],
        ],
        'table' => [
            'summary' => ['string', ''],
        ],
        'td' => [
            'abbr' => ['string', ''],
            'colSpan' => ['number', 'Maps to `colspan`'],
            'headers' => ['string', ''],
            'rowSpan' => ['number', 'Maps to `rowspan`'],
            'scope' => ['\'col\' | \'row\' | \'colgroup\' | \'rowgroup\'', ''],
        ],
        'text' => [
            'fill' => ['string', ''],
            'opacity' => ['number | string', ''],
            'stroke' => ['string', ''],
            'strokeWidth' => ['number | string', ''],
            'transform' => ['string', ''],
        ],
        'textarea' => [
            'autoComplete' => ['string', 'Maps to `autocomplete`'],
            'autoFocus' => ['boolean', 'Maps to `autofocus`'],
            'cols' => ['number', ''],
            'defaultValue' => ['string', ''],
            'dirname' => ['string', ''],
            'disabled' => ['boolean', ''],
            'enterKeyHint' => ['string', 'Maps to `enterkeyhint`'],
            'form' => ['string', ''],
            'inputMode' => ['string', 'Maps to `inputmode`'],
            'maxLength' => ['number', 'Maps to `maxlength`'],
            'minLength' => ['number', 'Maps to `minlength`'],
            'name' => ['string', ''],
            'placeholder' => ['string', ''],
            'readOnly' => ['boolean', 'Maps to `readonly`'],
            'required' => ['boolean', ''],
            'rows' => ['number', ''],
            'value' => ['string', ''],
            'wrap' => ['\'hard\' | \'soft\' | \'off\'', ''],
        ],
        'th' => [
            'abbr' => ['string', ''],
            'colSpan' => ['number', 'Maps to `colspan`'],
            'headers' => ['string', ''],
            'rowSpan' => ['number', 'Maps to `rowspan`'],
            'scope' => ['\'col\' | \'row\' | \'colgroup\' | \'rowgroup\'', ''],
        ],
        'time' => [
            'dateTime' => ['string', 'Maps to `datetime`'],
        ],
        'track' => [
            'default' => ['boolean', ''],
            'kind' => ['\'subtitles\' | \'captions\' | \'descriptions\' | \'chapters\' | \'metadata\'', ''],
            'label' => ['string', ''],
            'src' => ['string', ''],
            'srclang' => ['string', ''],
        ],
        'tspan' => [
            'fill' => ['string', ''],
            'opacity' => ['number | string', ''],
            'stroke' => ['string', ''],
            'strokeWidth' => ['number | string', ''],
            'transform' => ['string', ''],
        ],
        'video' => [
            'autoPlay' => ['boolean', 'Maps to `autoplay`'],
            'controls' => ['boolean', ''],
            'controlsList' => ['string', ''],
            'crossOrigin' => ['\'anonymous\' | \'use-credentials\' | \'\'', 'Maps to `crossorigin`'],
            'disablePictureInPicture' => ['boolean', ''],
            'disableRemotePlayback' => ['boolean', ''],
            'height' => ['number | string', ''],
            'loop' => ['boolean', ''],
            'muted' => ['boolean', ''],
            'playsInline' => ['boolean', 'Maps to `playsinline`'],
            'poster' => ['string', ''],
            'preload' => ['\'none\' | \'metadata\' | \'auto\' | \'\'', ''],
            'src' => ['string', ''],
            'width' => ['number | string', ''],
        ],
    ];
}
